# Generated by Django 5.0.4 on 2024-06-15 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='ano',
            new_name='año',
        ),
        migrations.AddField(
            model_name='ventavehiculo',
            name='color',
            field=models.CharField(choices=[('Blanco', 'Blanco'), ('Gris claro', 'Gris claro'), ('Gris oscuro', 'Gris oscuro'), ('Negro', 'Negro'), ('Rojo', 'Rojo'), ('Granate', 'Granate'), ('Azul', 'Azul'), ('Verde', 'Verde')], default='Negro', max_length=20),
        ),
        migrations.AlterField(
            model_name='ventavehiculo',
            name='precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado.precio'),
        ),
    ]
