# Generated by Django 5.0.4 on 2024-06-18 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0005_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='mercado.comentario')),
            ],
        ),
    ]
