# Generated by Django 5.0.4 on 2024-06-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0006_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventavehiculo',
            name='moneda',
        ),
    ]
