# Generated by Django 5.0.4 on 2024-06-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0007_remove_ventavehiculo_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='alt_combustible',
            field=models.CharField(blank=True, choices=[('Nafta', 'Nafta'), ('Diesel', 'Diesel'), ('GNC', 'GNC'), ('Electricidad', 'Electricidad')], default='Nafta', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='combustible',
            field=models.CharField(choices=[('Nafta', 'Nafta'), ('Diesel', 'Diesel'), ('GNC', 'GNC'), ('Electricidad', 'Electricidad')], default='Nafta', max_length=20),
        ),
    ]
