# Generated by Django 5.0.4 on 2024-06-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0008_vehiculo_alt_combustible_vehiculo_combustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='alt_combustible',
            field=models.CharField(blank=True, choices=[('Nafta', 'Nafta'), ('Diesel', 'Diesel'), ('GNC', 'GNC'), ('Electricidad', 'Electricidad')], max_length=20, null=True),
        ),
    ]
